# Generated by Django 4.2.6 on 2023-10-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysocial', '0019_delete_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('dop', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=150)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysocial.userprofile')),
            ],
        ),
    ]
