# Generated by Django 4.2.6 on 2023-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_userpost_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
