# Generated by Django 4.2.6 on 2023-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.CharField(default=22, max_length=10),
        ),
    ]
