# Generated by Django 4.2.6 on 2023-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_remove_userprofile_city_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
