# Generated by Django 4.2.6 on 2023-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0006_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='dop',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
