# Generated by Django 4.2.6 on 2023-10-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0009_remove_friendrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
