# Generated by Django 4.2.6 on 2023-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0013_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
