# Generated by Django 4.2.6 on 2023-10-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0015_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
