# Generated by Django 4.2.6 on 2023-10-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0018_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
