# Generated by Django 4.2.6 on 2023-11-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0019_delete_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
