# Generated by Django 4.2.6 on 2023-11-07 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0023_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='friendship_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friendship_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
