# Generated by Django 4.2.6 on 2023-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0024_remove_friendrequest_friendship_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friendship_at',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='friendship_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
