# Generated by Django 4.2.6 on 2023-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0031_friendrequest_different_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_user', models.F('to_user')), ('to_user', models.F('from_user')), _negated=True), fields=('from_user', 'to_user'), name='unique_from_to_user'),
        ),
    ]
