# Generated by Django 4.2.6 on 2023-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0032_friendrequest_unique_from_to_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_from_to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_user', models.F('to_user')), ('to_user', models.F('from_user'))), fields=('from_user', 'to_user'), name='reverse_unique_together'),
        ),
    ]
